SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DEVICE_ID) AS DEVICE_ID_NON_NULL,
    COUNT(PERSONA) AS PERSONA_NON_NULL,
    COUNT(HOME_LAT) AS HOME_LAT_NON_NULL,
    COUNT(HOME_LON) AS HOME_LON_NON_NULL,
    COUNT(NEAREST_STORE_ID) AS STORE_ID_NON_NULL
FROM CATCHMENT_DATA;
SELECT
    DEVICE_ID,
    COUNT(*) AS RECORD_COUNT
FROM CATCHMENT_DATA
GROUP BY DEVICE_ID
HAVING COUNT(*) > 1;
SELECT *
FROM CATCHMENT_DATA
WHERE HOME_LAT < -90
   OR HOME_LAT > 90;
   SELECT *
FROM CATCHMENT_DATA
WHERE HOME_LON < -180
   OR HOME_LON > 180;
SELECT
    c.NEAREST_STORE_ID,
    COUNT(*) AS CATCHMENT_DEVICES
FROM CATCHMENT_DATA c
GROUP BY c.NEAREST_STORE_ID
ORDER BY CATCHMENT_DEVICES DESC;
SELECT *
FROM CATCHMENT_DATA
LIMIT 5;
SELECT *
FROM TABLE(
    INFORMATION_SCHEMA.COPY_HISTORY(
        TABLE_NAME => 'CATCHMENT_DATA',
        START_TIME => DATEADD('hour', -24, CURRENT_TIMESTAMP())
    )
)
ORDER BY LAST_LOAD_TIME DESC;