-- Database
CREATE DATABASE IF NOT EXISTS GEOPULSE;

-- Schema
USE DATABASE GEOPULSE;

CREATE SCHEMA IF NOT EXISTS RETAIL_ANALYSIS;

-- Warehouse
CREATE WAREHOUSE IF NOT EXISTS GEOPULSE_WH
WAREHOUSE_SIZE = 'X-SMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

-- Role
CREATE ROLE IF NOT EXISTS GEOPULSE_ROLE;

-- Grants
GRANT USAGE ON DATABASE GEOPULSE
TO ROLE GEOPULSE_ROLE;

GRANT USAGE ON SCHEMA GEOPULSE.RETAIL_ANALYSIS
TO ROLE GEOPULSE_ROLE;

GRANT USAGE ON WAREHOUSE GEOPULSE_WH
TO ROLE GEOPULSE_ROLE;

GRANT SELECT ON ALL TABLES IN SCHEMA GEOPULSE.RETAIL_ANALYSIS
TO ROLE GEOPULSE_ROLE;