SHOW ROLES;

CREATE ROLE IF NOT EXISTS GEOPULSE_ROLE;

GRANT USAGE ON DATABASE GEOPULSE
TO ROLE GEOPULSE_ROLE;

GRANT USAGE ON SCHEMA GEOPULSE.RETAIL_ANALYSIS
TO ROLE GEOPULSE_ROLE;

GRANT SELECT ON ALL TABLES IN SCHEMA GEOPULSE.RETAIL_ANALYSIS
TO ROLE GEOPULSE_ROLE;

GRANT CREATE TABLE ON SCHEMA GEOPULSE.RETAIL_ANALYSIS
TO ROLE GEOPULSE_ROLE;

GRANT USAGE ON WAREHOUSE GEOPULSE_WH
TO ROLE GEOPULSE_ROLE;

SHOW GRANTS TO ROLE GEOPULSE_ROLE;

USE WAREHOUSE GEOPULSE_WH;

USE DATABASE GEOPULSE;

USE SCHEMA RETAIL_ANALYSIS;

SELECT CURRENT_ROLE();

SELECT CURRENT_WAREHOUSE();

SELECT * FROM GPS_DATA LIMIT 10;

SELECT * FROM FOOTFALL_SUMMARY;

SELECT * FROM DISTANCE_DATA LIMIT 10;

SELECT COUNT(*) AS GPS_ROWS
FROM GPS_DATA;

SELECT COUNT(*) AS FOOTFALL_ROWS
FROM FOOTFALL_SUMMARY;

SELECT COUNT(*) AS DISTANCE_ROWS
FROM DISTANCE_DATA;