USE DATABASE GEOPULSE;
USE SCHEMA RETAIL_ANALYSIS;
SELECT CURRENT_DATABASE(), CURRENT_SCHEMA();
DESC TABLE GPS_DATA;
DESC TABLE DISTANCE_DATA;
DESC TABLE FOOTFALL_SUMMARY;
SELECT COUNT(*) AS GPS_ROWS
FROM GPS_DATA;
SELECT COUNT(*) AS DISTANCE_ROWS
FROM DISTANCE_DATA;
SELECT COUNT(*) AS FOOTFALL_ROWS
FROM FOOTFALL_SUMMARY;
SELECT *
FROM GPS_DATA
LIMIT 10;
SELECT *
FROM DISTANCE_DATA
LIMIT 10;
SELECT *
FROM FOOTFALL_SUMMARY
LIMIT 10;
SELECT COUNT(*) AS NULL_DEVICE_ID
FROM GPS_DATA
WHERE DEVICE_ID IS NULL;
SELECT COUNT(*) AS INVALID_COORDINATES
FROM GPS_DATA
WHERE LAT NOT BETWEEN -90 AND 90
   OR LON NOT BETWEEN -180 AND 180;
SELECT COUNT(*) AS FUTURE_TIMESTAMPS
FROM GPS_DATA
WHERE TIMESTAMP > CURRENT_TIMESTAMP();
SELECT
    DEVICE_ID,
    TIMESTAMP,
    LAT,
    LON,
    COUNT(*) AS DUPLICATE_COUNT
FROM GPS_DATA
GROUP BY DEVICE_ID, TIMESTAMP, LAT, LON
HAVING COUNT(*) > 1;
SELECT COUNT(*) AS NEGATIVE_DISTANCE
FROM DISTANCE_DATA
WHERE DISTANCE < 0;
SELECT COUNT(*) AS NEGATIVE_FOOTFALL
FROM FOOTFALL_SUMMARY
WHERE FOOTFALL < 0;