-- ==========================================
-- GeoPulse - Week 1 Snowflake Setup
-- ==========================================

-- 1. Create Warehouse
CREATE WAREHOUSE IF NOT EXISTS GEOPULSE_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

USE WAREHOUSE GEOPULSE_WH;


-- 2. Create Database
CREATE DATABASE IF NOT EXISTS GEOPULSE_DB;

USE DATABASE GEOPULSE_DB;


-- 3. Create Schema
CREATE SCHEMA IF NOT EXISTS RAW;

USE SCHEMA RAW;


-- 4. Create Raw GPS Table
CREATE OR REPLACE TABLE GPS_PINGS_RAW (
    DEVICE_ID STRING,
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    EVENT_TIMESTAMP TIMESTAMP_NTZ
);


-- 5. Generate Mock GPS Data
INSERT INTO GPS_PINGS_RAW
SELECT
    'DEVICE_' || UNIFORM(1, 10000, RANDOM()) AS DEVICE_ID,
    17.35 + UNIFORM(0, 2000, RANDOM()) / 10000 AS LATITUDE,
    78.35 + UNIFORM(0, 2000, RANDOM()) / 10000 AS LONGITUDE,
    DATEADD(
        MINUTE,
        UNIFORM(0, 1440, RANDOM()),
        '2026-08-01 00:00:00'::TIMESTAMP_NTZ
    ) AS EVENT_TIMESTAMP
FROM TABLE(GENERATOR(ROWCOUNT => 100000));


-- 6. Create GPS Table with GEOGRAPHY
CREATE OR REPLACE TABLE GPS_PINGS (
    DEVICE_ID STRING,
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    EVENT_TIMESTAMP TIMESTAMP_NTZ,
    LOCATION GEOGRAPHY
);


-- 7. Convert Latitude/Longitude to GEOGRAPHY
INSERT INTO GPS_PINGS
(
    DEVICE_ID,
    LATITUDE,
    LONGITUDE,
    EVENT_TIMESTAMP,
    LOCATION
)
SELECT
    DEVICE_ID,
    LATITUDE,
    LONGITUDE,
    EVENT_TIMESTAMP,
    TO_GEOGRAPHY(
        'POINT(' || LONGITUDE || ' ' || LATITUDE || ')'
    )
FROM GPS_PINGS_RAW;


-- 8. Validate Record Count
SELECT COUNT(*) AS TOTAL_PINGS
FROM GEOPULSE_DB.RAW.GPS_PINGS;


-- 9. Validate NULL Values
SELECT
    COUNT_IF(DEVICE_ID IS NULL) AS NULL_DEVICE_ID,
    COUNT_IF(LATITUDE IS NULL) AS NULL_LATITUDE,
    COUNT_IF(LONGITUDE IS NULL) AS NULL_LONGITUDE,
    COUNT_IF(EVENT_TIMESTAMP IS NULL) AS NULL_TIMESTAMP,
    COUNT_IF(LOCATION IS NULL) AS NULL_LOCATION
FROM GEOPULSE_DB.RAW.GPS_PINGS;


-- 10. Validate Latitude
SELECT COUNT(*) AS INVALID_LATITUDE
FROM GEOPULSE_DB.RAW.GPS_PINGS
WHERE LATITUDE < -90 OR LATITUDE > 90;


-- 11. Validate Longitude
SELECT COUNT(*) AS INVALID_LONGITUDE
FROM GEOPULSE_DB.RAW.GPS_PINGS
WHERE LONGITUDE < -180 OR LONGITUDE > 180;


-- 12. Check Unique Devices
SELECT
    COUNT(DISTINCT DEVICE_ID) AS UNIQUE_DEVICES
FROM GEOPULSE_DB.RAW.GPS_PINGS;


-- 13. Check Timestamp Range
SELECT
    MIN(EVENT_TIMESTAMP) AS FIRST_PING,
    MAX(EVENT_TIMESTAMP) AS LAST_PING
FROM GEOPULSE_DB.RAW.GPS_PINGS;


-- 14. Check Geographic Range
SELECT
    MIN(LATITUDE) AS MIN_LATITUDE,
    MAX(LATITUDE) AS MAX_LATITUDE,
    MIN(LONGITUDE) AS MIN_LONGITUDE,
    MAX(LONGITUDE) AS MAX_LONGITUDE
FROM GEOPULSE_DB.RAW.GPS_PINGS;


-- 15. Validate GEOGRAPHY Points
SELECT
    COUNT(*) AS TOTAL_POINTS,
    COUNT_IF(LOCATION IS NOT NULL) AS VALID_GEOGRAPHY_POINTS
FROM GEOPULSE_DB.RAW.GPS_PINGS;


-- 16. Check GEOGRAPHY Type
SELECT TYPEOF(LOCATION) AS LOCATION_TYPE
FROM GEOPULSE_DB.RAW.GPS_PINGS
LIMIT 1;


-- 17. Check Duplicate Records
SELECT
    DEVICE_ID,
    LATITUDE,
    LONGITUDE,
    EVENT_TIMESTAMP,
    COUNT(*) AS DUPLICATE_COUNT
FROM GEOPULSE_DB.RAW.GPS_PINGS
GROUP BY
    DEVICE_ID,
    LATITUDE,
    LONGITUDE,
    EVENT_TIMESTAMP
HAVING COUNT(*) > 1;


-- 18. Hourly Footfall
SELECT
    DATE_TRUNC('HOUR', EVENT_TIMESTAMP) AS HOUR,
    COUNT(*) AS TOTAL_PINGS,
    COUNT(DISTINCT DEVICE_ID) AS UNIQUE_DEVICES
FROM GEOPULSE_DB.RAW.GPS_PINGS
GROUP BY HOUR
ORDER BY HOUR;


-- 19. Create Validation View
CREATE OR REPLACE VIEW GPS_PINGS_VALIDATED AS
SELECT
    DEVICE_ID,
    LATITUDE,
    LONGITUDE,
    EVENT_TIMESTAMP,
    LOCATION
FROM GPS_PINGS
WHERE DEVICE_ID IS NOT NULL
  AND LATITUDE BETWEEN -90 AND 90
  AND LONGITUDE BETWEEN -180 AND 180
  AND EVENT_TIMESTAMP IS NOT NULL
  AND LOCATION IS NOT NULL;
