{{ config(
    materialized='view'
) }}

SELECT
    DEVICE_ID,
    LATITUDE,
    LONGITUDE,
    EVENT_TIMESTAMP,
    LOCATION,
    DATE_TRUNC('HOUR', EVENT_TIMESTAMP) AS EVENT_HOUR
FROM GEOPULSE_DB.RAW.GPS_PINGS
WHERE DEVICE_ID IS NOT NULL
  AND LATITUDE BETWEEN -90 AND 90
  AND LONGITUDE BETWEEN -180 AND 180
  AND EVENT_TIMESTAMP IS NOT NULL
  AND LOCATION IS NOT NULL