CREATE OR REPLACE TABLE CATCHMENT_DATA (
    DEVICE_ID VARCHAR,
    PERSONA VARCHAR,
    HOME_LAT FLOAT,
    HOME_LON FLOAT,
    NEAREST_STORE_ID VARCHAR,
    NEAREST_STORE_NAME VARCHAR,
    DISTANCE_TO_NEAREST_STORE_M FLOAT,
    CATCHMENT_RING VARCHAR,
    DIST_TO_STR001_M FLOAT,
    DIST_TO_STR002_M FLOAT,
    DIST_TO_STR003_M FLOAT,
    CATCHMENT_OVERLAP_COUNT INTEGER,
    OVERLAPPING_STORES VARCHAR,
    VISITED_ANY_STORE BOOLEAN
);
SHOW TABLES;