SELECT COUNT(*) AS TOTAL_ROWS
FROM CATCHMENT_DATA;
DESC TABLE CATCHMENT_DATA;
SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DEVICE_ID) AS DEVICE_ID_NON_NULL,
    COUNT(PERSONA) AS PERSONA_NON_NULL,
    COUNT(HOME_LAT) AS HOME_LAT_NON_NULL,
    COUNT(HOME_LON) AS HOME_LON_NON_NULL,
    COUNT(NEAREST_STORE_ID) AS STORE_ID_NON_NULL
FROM CATCHMENT_DATA;
SELECT
    DEVICE_ID,
    COUNT(*) AS RECORD_COUNT
FROM CATCHMENT_DATA
GROUP BY DEVICE_ID
HAVING COUNT(*) > 1;
SELECT *
FROM CATCHMENT_DATA
WHERE HOME_LAT < -90
   OR HOME_LAT > 90;
SELECT *
FROM CATCHMENT_DATA
WHERE HOME_LON < -180
   OR HOME_LON > 180;
SELECT *
FROM CATCHMENT_DATA
WHERE DISTANCE_TO_NEAREST_STORE_M < 0
   OR DIST_TO_STR001_M < 0
   OR DIST_TO_STR002_M < 0
   OR DIST_TO_STR003_M < 0;
SELECT
    VISITED_ANY_STORE,
    COUNT(*) AS TOTAL
FROM CATCHMENT_DATA
GROUP BY VISITED_ANY_STORE;
SELECT *
FROM CATCHMENT_DATA
LIMIT 10;
SELECT
    DEVICE_ID,
    PERSONA,
    HOME_LAT,
    HOME_LON,
    NEAREST_STORE_ID,
    NEAREST_STORE_NAME,
    DISTANCE_TO_NEAREST_STORE_M,
    VISITED_ANY_STORE
FROM CATCHMENT_DATA
LIMIT 10;
SELECT *
FROM TABLE(
    INFORMATION_SCHEMA.COPY_HISTORY(
        TABLE_NAME=>'CATCHMENT_DATA',
        START_TIME=>DATEADD('hour', -24, CURRENT_TIMESTAMP())
    )
)
ORDER BY LAST_LOAD_TIME DESC;
